/**
 * The service catalogue.
 *
 * `implemented` is the column that matters. A service marked true is running
 * code in this repository; one marked false is declared — the system plainly
 * has to do that job, the entry says what the job is and where it is
 * configured, and it does not pretend to be measuring or moving anything. The
 * task manager prints the distinction rather than hiding it.
 *
 * The names are Lumen's own. The catalogue covers the ground a desktop
 * system's service list covers — input methods, printing, sync, accessibility,
 * maintenance — without borrowing another vendor's binaries, which would name
 * products this system does not have.
 */

import type { ServiceDefinition } from './types';

export const SERVICES: readonly ServiceDefinition[] = [
  {
    id: 'com.lumen.kernel',
    name: 'Kernel Supervisor',
    category: 'core',
    description: 'Starts the other services and keeps the process table.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.windowserver',
    name: 'Window Server',
    category: 'core',
    description: 'Owns window geometry, stacking order and focus.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.processmanager',
    name: 'Process Manager',
    category: 'core',
    description: 'Starts and ends processes and reports what they cost.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.settingsd',
    name: 'Settings Store',
    category: 'core',
    description: 'Reads and writes every setting, and tells the system when one changes.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'general',
  },
  {
    id: 'com.lumen.eventbus',
    name: 'Event Bus',
    category: 'core',
    description: 'Carries system events between the kernel, the shell and applications.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.sessiond',
    name: 'Session Manager',
    category: 'core',
    description: 'Signs a user in and out and holds the state of the session.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.logd',
    name: 'System Log',
    category: 'core',
    description: 'Collects kernel events, notifications and errors for Console.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.launchd',
    name: 'Service Manager',
    category: 'core',
    description: 'Starts services in dependency order and restarts the ones that stop.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.timed',
    name: 'Clock and Time Zones',
    category: 'core',
    description: 'Keeps the clock and applies the time zone.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'region',
  },
  {
    id: 'com.lumen.localed',
    name: 'Locale and Formats',
    category: 'core',
    description: 'Decides how dates, numbers and units are written.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'region',
  },
  {
    id: 'com.lumen.powerd',
    name: 'Power Management',
    category: 'core',
    description: 'Watches the battery and puts the display to sleep.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'power',
  },
  {
    id: 'com.lumen.thermald',
    name: 'Thermal Monitor',
    category: 'core',
    description: 'Reads temperature and asks for less work when it is high.',
    startup: 'boot',
    implemented: false,
  },
  {
    id: 'com.lumen.crashd',
    name: 'Crash Reporter',
    category: 'core',
    description: 'Catches an application that stops responding and offers to relaunch it.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.dock',
    name: 'Dock',
    category: 'shell',
    description: 'Draws the taskbar and its running-application list.',
    startup: 'login',
    implemented: true,
    settingsSection: 'taskbar',
  },
  {
    id: 'com.lumen.menubar',
    name: 'Menu Bar',
    category: 'shell',
    description: 'Draws the system bar and the menus of the focused application.',
    startup: 'login',
    implemented: true,
    settingsSection: 'menubar',
  },
  {
    id: 'com.lumen.desktop',
    name: 'Desktop',
    category: 'shell',
    description: 'Draws the desktop and the icons on it, on behalf of the file manager.',
    startup: 'login',
    implemented: true,
    settingsSection: 'desktop',
  },
  {
    id: 'com.lumen.spotlight',
    name: 'Search',
    category: 'shell',
    description: 'Answers the search field in the start menu and Spotlight.',
    startup: 'login',
    implemented: true,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.notificationd',
    name: 'Notification Centre',
    category: 'shell',
    description: 'Queues notifications, shows banners and keeps the history.',
    startup: 'login',
    implemented: true,
    settingsSection: 'notifications',
  },
  {
    id: 'com.lumen.controlcenter',
    name: 'Control Centre',
    category: 'shell',
    description: 'The quick settings panel in the system bar.',
    startup: 'login',
    implemented: true,
    settingsSection: 'menubar',
  },
  {
    id: 'com.lumen.screensaverd',
    name: 'Screensaver',
    category: 'shell',
    description: 'Draws the screensaver once the machine has been idle long enough.',
    startup: 'triggered',
    implemented: true,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.lockd',
    name: 'Lock Screen',
    category: 'shell',
    description: 'Locks the screen and takes the password to unlock it.',
    startup: 'triggered',
    implemented: true,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.cursord',
    name: 'Cursor',
    category: 'shell',
    description: 'Draws the cursor and picks its shape from what is under it.',
    startup: 'login',
    implemented: true,
    settingsSection: 'cursor',
  },
  {
    id: 'com.lumen.overview',
    name: 'Window Overview',
    category: 'shell',
    description: 'Shows every window at once, grouped by application.',
    startup: 'triggered',
    implemented: true,
    settingsSection: 'display',
  },
  {
    id: 'com.lumen.wallpaperd',
    name: 'Wallpaper',
    category: 'shell',
    description: 'Draws the desktop picture and derives the chrome tint from it.',
    startup: 'login',
    implemented: true,
    settingsSection: 'wallpaper',
  },
  {
    id: 'com.lumen.dialogd',
    name: 'Dialog Service',
    category: 'shell',
    description: 'Puts errors and messages on screen as windows of their own.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.rund',
    name: 'Run',
    category: 'shell',
    description: 'Opens a folder, an application or an address typed by hand.',
    startup: 'manual',
    implemented: false,
  },
  {
    id: 'com.lumen.setupd',
    name: 'Setup Assistant',
    category: 'shell',
    description: 'Creates a profile and walks through first setup. Hidden from the launcher.',
    startup: 'triggered',
    implemented: true,
  },
  {
    id: 'com.lumen.quicklookd',
    name: 'Quick Look',
    category: 'shell',
    description: 'Previews a file without opening the application that owns it.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.filesd',
    name: 'File Manager',
    category: 'files',
    description: 'The file manager itself, which owns the desktop and never exits.',
    startup: 'login',
    implemented: true,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.vfsd',
    name: 'File System',
    category: 'files',
    description: 'The file system every application reads and writes through.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.indexerd',
    name: 'Search Index',
    category: 'files',
    description: 'Keeps the index that makes searching files quick.',
    startup: 'login',
    implemented: false,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.trashd',
    name: 'Trash',
    category: 'files',
    description: 'Holds deleted files until the Trash is emptied.',
    startup: 'login',
    implemented: true,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.thumbnaild',
    name: 'Thumbnails',
    category: 'files',
    description: 'Draws the small previews shown in icon and card views.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'files',
  },
  {
    id: 'com.lumen.archived',
    name: 'Archive Service',
    category: 'files',
    description: 'Reads and writes ZIP archives for the file manager.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.fsevents',
    name: 'File System Events',
    category: 'files',
    description: 'Tells applications when a file or folder they are showing has changed.',
    startup: 'boot',
    implemented: true,
  },
  {
    id: 'com.lumen.volumed',
    name: 'Volume Mounter',
    category: 'files',
    description: 'Mounts and unmounts disk images and removable volumes.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.folderactions',
    name: 'Folder Actions',
    category: 'files',
    description: 'Runs a chosen action when a watched folder changes.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.hostbridged',
    name: 'Host File Bridge',
    category: 'files',
    description: 'Carries files between Lumen and the computer it runs on, with permission.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.netd',
    name: 'Network',
    category: 'network',
    description: 'Brings the network up and reports whether it is reachable.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.wifid',
    name: 'Wi-Fi',
    category: 'network',
    description: 'Finds networks and joins the chosen one.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.bluetoothd',
    name: 'Bluetooth',
    category: 'network',
    description: 'Pairs and connects nearby devices.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.dnsd',
    name: 'Name Resolution',
    category: 'network',
    description: 'Turns host names into addresses.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.httpd',
    name: 'HTTP Client',
    category: 'network',
    description:
      'Makes the requests applications ask for, and refuses them when the network is off.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.proxyd',
    name: 'Proxy Configuration',
    category: 'network',
    description: 'Applies the proxy the network requires.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.captived',
    name: 'Captive Portal Assistant',
    category: 'network',
    description: 'Notices a network that wants a sign-in page and opens it.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.sharingd',
    name: 'Nearby Sharing',
    category: 'network',
    description: 'Sends files to and from nearby machines.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.vpnd',
    name: 'VPN',
    category: 'network',
    description: 'Holds the encrypted tunnel while it is switched on.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.firewalld',
    name: 'Firewall',
    category: 'network',
    description: 'Decides which connections applications may open.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.timesyncd',
    name: 'Network Time',
    category: 'network',
    description: 'Corrects the clock against a time server.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'region',
  },
  {
    id: 'com.lumen.downloadd',
    name: 'Download Manager',
    category: 'network',
    description: 'Fetches files from the network into the download folder.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'network',
  },
  {
    id: 'com.lumen.webviewd',
    name: 'Web View Host',
    category: 'network',
    description: 'Runs a page in a window of its own, without an address bar or tools.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.keyboardd',
    name: 'Keyboard',
    category: 'input',
    description: 'Reads the keyboard and applies the layout.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.shortcutd',
    name: 'Shortcuts',
    category: 'input',
    description: 'Matches key combinations and dispatches the action they name.',
    startup: 'login',
    implemented: true,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.pointerd',
    name: 'Pointer',
    category: 'input',
    description: 'Reads the mouse and trackpad, and applies speed and scrolling settings.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'cursor',
  },
  {
    id: 'com.lumen.imed',
    name: 'Input Methods',
    category: 'input',
    description: 'Switches between the installed ways of typing.',
    startup: 'login',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.pinyin',
    name: 'Pinyin Input',
    category: 'input',
    description: 'Types Chinese from Latin letters.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.zhuyin',
    name: 'Zhuyin Input',
    category: 'input',
    description: 'Types Chinese from Bopomofo.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.kana',
    name: 'Kana Input',
    category: 'input',
    description: 'Types Japanese from the kana keyboard.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.romaji',
    name: 'Romaji Input',
    category: 'input',
    description: 'Types Japanese from Latin letters.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.hangul',
    name: 'Hangul Input',
    category: 'input',
    description: 'Types Korean.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.ime.vietnamese',
    name: 'Vietnamese Input',
    category: 'input',
    description: 'Types Vietnamese with tone marks.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.emojid',
    name: 'Symbols and Emoji',
    category: 'input',
    description: 'The character picker, and search across it.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.dictationd',
    name: 'Dictation',
    category: 'input',
    description: 'Turns speech into text in the field that has focus.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.textreplacementd',
    name: 'Text Replacement',
    category: 'input',
    description: 'Expands the shorthand the user has defined.',
    startup: 'login',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.spelld',
    name: 'Spelling and Grammar',
    category: 'input',
    description: 'Checks text as it is typed.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'keyboard',
  },
  {
    id: 'com.lumen.audiod',
    name: 'Audio',
    category: 'media',
    description: 'Owns the output device and mixes what applications play.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'sound',
  },
  {
    id: 'com.lumen.mixerd',
    name: 'Volume Mixer',
    category: 'media',
    description: 'Holds the volume of each application separately.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'sound',
  },
  {
    id: 'com.lumen.videod',
    name: 'Video Decode',
    category: 'media',
    description: 'Decodes video for the media player and previews.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.camerad',
    name: 'Camera',
    category: 'media',
    description: 'Opens the camera for the applications allowed to use it.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.screencaptured',
    name: 'Screen Capture',
    category: 'media',
    description: 'Takes screenshots and records the screen.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.speechd',
    name: 'Speech Synthesis',
    category: 'media',
    description: 'Reads text aloud.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.speechrecognitiond',
    name: 'Speech Recognition',
    category: 'media',
    description: 'Turns recorded speech into text.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.nowplayingd',
    name: 'Now Playing',
    category: 'media',
    description: 'Reports what is playing to the system bar and the lock screen.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'sound',
  },
  {
    id: 'com.lumen.streamd',
    name: 'Screen Streaming',
    category: 'media',
    description: 'Sends the display to another screen on the network.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'display',
  },
  {
    id: 'com.lumen.colorsyncd',
    name: 'Colour Management',
    category: 'media',
    description: 'Applies the display profile so colours match between screens.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'display',
  },
  {
    id: 'com.lumen.fontd',
    name: 'Font Registry',
    category: 'media',
    description: 'Registers the installed fonts and answers requests for them.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'appearance',
  },
  {
    id: 'com.lumen.printd',
    name: 'Print Spooler',
    category: 'printing',
    description: 'Queues documents and sends them to the printer.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.scand',
    name: 'Scanner',
    category: 'printing',
    description: 'Drives a scanner and hands the image to an application.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.pdfd',
    name: 'PDF Service',
    category: 'printing',
    description: 'Renders documents to PDF for printing and export.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.printerdiscoveryd',
    name: 'Printer Discovery',
    category: 'printing',
    description: 'Finds printers on the network.',
    startup: 'boot',
    implemented: false,
  },
  {
    id: 'com.lumen.authd',
    name: 'Authentication',
    category: 'security',
    description: 'Checks passwords and answers whether an action is allowed.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.keychaind',
    name: 'Keychain',
    category: 'security',
    description: 'Stores passwords and keys, locked with the account password.',
    startup: 'login',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.sudod',
    name: 'Privilege Broker',
    category: 'security',
    description: 'Grants administrator rights for one command, after a password.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.permissiond',
    name: 'Permission Prompts',
    category: 'security',
    description: 'Asks the user before an application reaches something private.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.malwared',
    name: 'Malware Scan',
    category: 'security',
    description: 'Checks installed programs against known-bad signatures.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.integrityd',
    name: 'System Integrity',
    category: 'security',
    description:
      'Refuses changes to system folders that did not come through the terminal under sudo.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.parentald',
    name: 'Screen Time and Limits',
    category: 'security',
    description: 'Applies the limits set for this account.',
    startup: 'login',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.certd',
    name: 'Certificate Trust',
    category: 'security',
    description: 'Decides which certificate authorities are trusted.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.recoveryd',
    name: 'Recovery',
    category: 'security',
    description: 'Starts the recovery environment when the system cannot.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.escrowd',
    name: 'Recovery Key Escrow',
    category: 'security',
    description: 'Holds the recovery key made when the account was created.',
    startup: 'triggered',
    implemented: true,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.accountsd',
    name: 'Accounts',
    category: 'sync',
    description: 'Holds the accounts applications sign in with.',
    startup: 'login',
    implemented: false,
    settingsSection: 'security',
  },
  {
    id: 'com.lumen.cloudd',
    name: 'Cloud Sync',
    category: 'sync',
    description: 'Keeps the synchronised folders up to date.',
    startup: 'login',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.contactsyncd',
    name: 'Contact Sync',
    category: 'sync',
    description: 'Merges contacts between the accounts that carry them.',
    startup: 'login',
    implemented: false,
  },
  {
    id: 'com.lumen.calendarsyncd',
    name: 'Calendar Sync',
    category: 'sync',
    description: 'Fetches and publishes calendar changes.',
    startup: 'login',
    implemented: false,
  },
  {
    id: 'com.lumen.maild',
    name: 'Mail Fetch',
    category: 'sync',
    description: 'Collects mail in the background and files it.',
    startup: 'login',
    implemented: false,
    settingsSection: 'notifications',
  },
  {
    id: 'com.lumen.messaged',
    name: 'Messages',
    category: 'sync',
    description: 'Delivers messages and their read state.',
    startup: 'login',
    implemented: false,
    settingsSection: 'notifications',
  },
  {
    id: 'com.lumen.remindersd',
    name: 'Reminders',
    category: 'sync',
    description: 'Fires reminders when they fall due.',
    startup: 'login',
    implemented: false,
    settingsSection: 'notifications',
  },
  {
    id: 'com.lumen.notessyncd',
    name: 'Notes Sync',
    category: 'sync',
    description: 'Keeps notes the same on every machine signed in.',
    startup: 'login',
    implemented: false,
  },
  {
    id: 'com.lumen.photosyncd',
    name: 'Photo Sync',
    category: 'sync',
    description: 'Uploads and downloads the photo library.',
    startup: 'login',
    implemented: false,
  },
  {
    id: 'com.lumen.storesyncd',
    name: 'Store Catalogue',
    category: 'sync',
    description: 'Keeps the application catalogue and its prices current.',
    startup: 'login',
    implemented: false,
    settingsSection: 'updates',
  },
  {
    id: 'com.lumen.updated',
    name: 'Software Update',
    category: 'maintenance',
    description: 'Checks for system and application updates in the background.',
    startup: 'login',
    implemented: false,
    settingsSection: 'updates',
  },
  {
    id: 'com.lumen.installerd',
    name: 'Installer',
    category: 'maintenance',
    description: 'Unpacks and installs an application, and reports its progress.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'updates',
  },
  {
    id: 'com.lumen.uninstalld',
    name: 'Uninstaller',
    category: 'maintenance',
    description: 'Removes an application and the files it registered.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'updates',
  },
  {
    id: 'com.lumen.backupd',
    name: 'Backup',
    category: 'maintenance',
    description: 'Copies the home folder to the chosen destination on a schedule.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.snapshotd',
    name: 'Snapshots',
    category: 'maintenance',
    description: 'Keeps point-in-time copies of the file system.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.cached',
    name: 'Cache Cleaner',
    category: 'maintenance',
    description: 'Clears caches when disk space runs short.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.diagnosticsd',
    name: 'Diagnostics',
    category: 'maintenance',
    description: 'Collects a report about the machine for support.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'privacy',
  },
  {
    id: 'com.lumen.metricsd',
    name: 'Performance Metrics',
    category: 'maintenance',
    description: 'Measures what each process costs, for the task manager.',
    startup: 'boot',
    implemented: true,
    settingsSection: 'display',
  },
  {
    id: 'com.lumen.migrationd',
    name: 'Migration Assistant',
    category: 'maintenance',
    description: 'Moves an account and its files from another machine.',
    startup: 'manual',
    implemented: false,
  },
  {
    id: 'com.lumen.diskcheckd',
    name: 'Disk Check',
    category: 'maintenance',
    description: 'Verifies and repairs the file system.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.storagemgmtd',
    name: 'Storage Management',
    category: 'maintenance',
    description: 'Finds what is filling the disk and offers to clear it.',
    startup: 'triggered',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.quotad',
    name: 'Storage Quotas',
    category: 'maintenance',
    description: 'Holds each account to its share of the disk.',
    startup: 'boot',
    implemented: false,
    settingsSection: 'storage',
  },
  {
    id: 'com.lumen.a11yd',
    name: 'Accessibility',
    category: 'accessibility',
    description: 'Applies the accessibility settings across the system.',
    startup: 'login',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.voiceoverd',
    name: 'Screen Reader',
    category: 'accessibility',
    description: 'Reads the interface aloud and moves focus by keyboard.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.zoomd',
    name: 'Screen Zoom',
    category: 'accessibility',
    description: 'Magnifies part of the screen.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.displayfilterd',
    name: 'Display Filters',
    category: 'accessibility',
    description: 'Applies colour filters and increased contrast.',
    startup: 'login',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.switchd',
    name: 'Switch Control',
    category: 'accessibility',
    description: 'Drives the interface from a single switch or key.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.captionsd',
    name: 'Captions',
    category: 'accessibility',
    description: 'Styles and shows captions over video.',
    startup: 'login',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.stickykeysd',
    name: 'Sticky Keys',
    category: 'accessibility',
    description: 'Lets a modifier be pressed and released before the key it modifies.',
    startup: 'login',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.visualalertd',
    name: 'Visual Alerts',
    category: 'accessibility',
    description: 'Flashes the screen in place of an alert sound.',
    startup: 'login',
    implemented: false,
    settingsSection: 'accessibility',
  },
  {
    id: 'com.lumen.debugd',
    name: 'Developer Debug',
    category: 'developer',
    description: 'Catches defects and files them against the repository.',
    startup: 'manual',
    implemented: false,
  },
  {
    id: 'com.lumen.inspectord',
    name: 'Inspector',
    category: 'developer',
    description: 'Shows the tree of windows and elements under the pointer.',
    startup: 'manual',
    implemented: false,
  },
  {
    id: 'com.lumen.i18nd',
    name: 'Localisation Reporter',
    category: 'developer',
    description: 'Collects untranslated strings and proposes corrections.',
    startup: 'manual',
    implemented: false,
    settingsSection: 'region',
  },
  {
    id: 'com.lumen.automationd',
    name: 'Automation',
    category: 'developer',
    description: 'Runs saved sequences of actions on behalf of the user.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.scriptd',
    name: 'Script Runner',
    category: 'developer',
    description: 'Runs a script with the permissions of the account.',
    startup: 'triggered',
    implemented: false,
  },
  {
    id: 'com.lumen.profilerd',
    name: 'Profiler',
    category: 'developer',
    description: 'Records where time goes while the system runs.',
    startup: 'manual',
    implemented: false,
  },
];

export function serviceById(id: string): ServiceDefinition | undefined {
  return SERVICES.find((service) => service.id === id);
}

export function servicesByCategory(
  category: ServiceDefinition['category'],
): readonly ServiceDefinition[] {
  return SERVICES.filter((service) => service.category === category);
}

/** Services the system starts on its own, in the order it starts them. */
export function autostartServices(): readonly ServiceDefinition[] {
  const order = { boot: 0, login: 1, triggered: 2, manual: 3 };
  return SERVICES.filter((s) => s.startup === 'boot' || s.startup === 'login').sort(
    (a, b) => order[a.startup] - order[b.startup],
  );
}
